name: schedule

on:
  schedule:
    - cron:  "00 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: get_json
      run: curl ${{ secrets.GET_JSON_URL }}
