name: send_data_to_firestore

on:
  schedule:
    - cron:  "*/15 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install requirements.txt
      run: curl ${{ secrets.CLOUD_FUNCTIONS_TRIGGER }}
