
name: Get Prefectrures Data

on:
  schedule:
    - cron:  "*/15 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install requirements.txt
      run: |
        sudo apt-get install python3-setuptools
        pip3 install -r get_prefectures_data/requirements.txt

    - name: save firestore
      run: python3 get_prefectures_data/get_prefectures_data.py
      env:
        type: ${{ secrets.type }}
        project_id: ${{ secrets.project_id }}
        private_key_id: ${{ secrets.private_key_id }}
        private_key: ${{ secrets.private_key }}
        client_email: ${{ secrets.client_email }}
        client_id: ${{ secrets.client_id }}
        auth_uri: ${{ secrets.auth_uri }}
        token_uri: ${{ secrets.token_uri }}
        auth_provider_x509_cert_url: ${{ secrets.auth_provider_x509_cert_url }}
        client_x509_cert_url: ${{ secrets.client_x509_cert_url}}
        
        
